### ISSUE TITLE
Handle "The DTLS handshake timed out" promise rejection

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-tradfri-client#45]
see https://github.com/AlCalzone/node-tradfri-client/issues/44#issuecomment-372116455

**Comment by neophob** [comment]
for reference, this is the error I captured

```
Error: The DTLS handshake timed out
    at normalizeReason (/myproject/node_modules/node-coap-client/build/lib/DeferredPromise.js:5:16)
    at Promise.rej [as reject] (/myproject/node_modules/node-coap-client/build/lib/DeferredPromise.js:13:36)
    at Socket.onError (/myproject/node_modules/node-coap-client/build/CoapClient.js:964:25)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)    
    at Socket.emit (events.js:211:7)
    at Socket.killConnection (/myproject/node_modules/node-dtls-client/build/dtls.js:236:22)
    at Socket.expectHandshake (/myproject/node_modules/node-dtls-client/build/dtls.js:152:22)
    at Timeout.<anonymous> (/myproject/node_modules/node-dtls-client/build/dtls.js:109:77)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by AlCalzone** [comment]
Same as with `CoapClient was reset`: Do you think that swallowing the error and instead emitting a library error is good from a user's point of view? Again the documentation must state that pending promises will never resolve or reject.

**Comment by MilongWong** [comment]
I have the same problem. And solved when enable the firewall inbound rule for UDP Port (e.g., 443)
