### ISSUE TITLE
Unhandled error when deleting moods through the app

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-tradfri-client#88]
Caught | 2018-05-05 15:25:52.953 | error | by controller[0]:     at PendingRequest.handleResponse [as callback]  (/opt/iobroker/node_modules/node-tradfri-client/build/tradfri-client.js:519:41)
-- | -- | -- | --
Caught | 2018-05-05 15:25:52.952 | error | by controller[0]:     at TradfriClient.observeScene_callback  (/opt/iobroker/node_modules/node-tradfri-client/build/tradfri-client.js:553:23)
Caught | 2018-05-05 15:25:52.952 | error | by controller[0]:     at TradfriClient.handleNonSuccessfulResponse  (/opt/iobroker/node_modules/node-tradfri-client/build/tradfri-client.js:578:25)
Caught | 2018-05-05 15:25:52.952 | error | by controller[0]:     at parsePayload (/opt/iobroker/node_modules/node-tradfri-client/build/tradfri-client.js:757:25)
Caught | 2018-05-05 15:25:52.952 | error | by controller[0]:     at JSON.parse (<anonymous>)
Caught | 2018-05-05 15:25:52.951 | error | by controller[0]: SyntaxError: Unexpected end of JSON i

**Comment by AlCalzone** [comment]
Already fixed by 7bf8db8
