### ISSUE TITLE
Compatibility with electron

### ISSUE THREAD

**Issue by BeMacized** [AlCalzone/node-tradfri-client#91]
First of all, apologies if this isn't the right place to ask. I have been running into problems getting this module to work with Electron and am not entirely sure where to turn to.

The issue I am running into is that while my application builds fine, it crashes during runtime the moment I try to run the authentication method:
```javascript
const {identity, psk} = await tradfri.authenticate(securityCode);
```

The exact error that occurs is the following:
```
/home/bemacized/Development/Git/Personal/tradfri-tray/node_modules/electron/dist/electron --serve .: symbol lookup error: /home/bemacized/Development/Git/Personal/tradfri-tray/node_modules/node-aead-crypto/build/Release/electron-v2.0-linux-x64/node_aead_crypto.node: undefined symbol: EVP_aes_128_ccm
```

It does not matter whether this is executed in electron's main process or one of the renderer processes, the same error always occurs. This problem does not occur when calling the same method in a regular node application, without electron. 

There is a duplicate issue over at [electron-rebuild#226](https://github.com/electron/electron-rebuild/issues/226) from earlier this February which sadly has still gone unsolved.

My environment is follows:

- node v10.1.0
- npm v6.0.1
- yarn 1.6.0
- electron 2.0.1
- electron-builder 20.13.4
- node-aead-crypto 1.1.3
- node-tradfri-client 1.2.1
- OS: Arch Linux

The `post-install` script within my package.json has been set to execute `npx electron-builder install-app-deps`.

Any information regarding getting this to run with Electron would be greatly appreciated.

**Comment by AlCalzone** [comment]
I'm not familiar with electron, but at a first glance you shouldn't even need the failing module since you're on NodeJS 10. Can you please check the versions of
* node-coap-client (should be 0.7.2)
* node-dtls-client (should be 0.5.4)

When installing node-dtls-client, there should be a log output indicating that the installation of node-aead-crypto is skippped, since you're on NodeJS 10.

**Comment by BeMacized** [comment]
The versions for node-coap-client and node-dtls-client seem to match those you specified. I tried installing both modules, but neither produced any log entry about skipping the installation of node-aead-crypto. 

When trying to run the project without node-aead-crypto installed, an error appears indicating the module could not be found: 
<details>
<summary>Stacktrace</summary>
<pre>
App threw an error during load
Error: Cannot find module 'node-aead-crypto'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/bemacized/Development/Git/Personal/tradfri-tray/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/bemacized/Development/Git/Personal/tradfri-tray/node_modules/node-dtls-client/build/lib/AEADCrypto.js:54:47)
    at Object.<anonymous> (/home/bemacized/Development/Git/Personal/tradfri-tray/node_modules/node-dtls-client/build/lib/AEADCrypto.js:59:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'node-aead-crypto'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/bemacized/Development/Git/Personal/tradfri-tray/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/bemacized/Development/Git/Personal/tradfri-tray/node_modules/node-dtls-client/build/lib/AEADCrypto.js:54:47)
    at Object.<anonymous> (/home/bemacized/Development/Git/Personal/tradfri-tray/node_modules/node-dtls-client/build/lib/AEADCrypto.js:59:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
</pre>
</details>


As it turns out, electron uses a separate node version for its processes, rather than the one I have installed on my machine. The Node version is actually v8.9.3. I assume this is why node-aead-crypto is still required?

While I am not entirely sure whether it is relevant, the version electron reports for openssl is v1.0.2n.

**Comment by AlCalzone** [comment]
I'm afraid I won't be able to help too much here. You could try rebuilding node-aead-crypto and take a look at the full output to see if there are warnings related to that missing symbol.

**Comment by AlCalzone** [comment]
> I have to confess that working with native modules is not something I know very much about.

To be honest, neither do I. I started with code that already existed and made it work on Windows and with precompiling through lots of googling ;)
That module is always a source of problems, so I'm happy it won't be needed starting with Node 10.

**Comment by franzwilhelm** [comment]
Hi @AlCalzone & @BeMacized. I kinda figured out how to solve this with NodeJS > 10 in electron. I'm using rollup, and literally all I had to do was adding node-aead-crypto as an external package, and link it as a global to target the builtin crypto package. Webpack also has options on this: https://webpack.js.org/configuration/externals/ & https://webpack.js.org/guides/shimming/. For reference, here is my rollup.config.js (ignore the parts related to other stuff):

```js
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import json from 'rollup-plugin-json';
import { terser } from 'rollup-plugin-terser';
import sass from 'node-sass';
import builtins from 'rollup-plugin-node-builtins';
import globals from 'rollup-plugin-node-globals';

const production = !process.env.ROLLUP_WATCH;
export default {
	input: 'src/App.js',
	external: [
		'node-aead-crypto'
	],
	output: {
		sourcemap: false,
		format: 'iife',
		name: 'app',
		file: 'public/bundle.js',
		globals: {
			'node-aead-crypto': 'crypto',
		},
	},
	plugins: [
		svelte({
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file — better for performance
			css: css => {
				css.write('public/bundle.css');
			},
			preprocess: {
				style: async ({ content, attributes }) => {
					if (attributes.type !== 'text/scss' && attributes.lang !== 'scss') return;

					return new Promise((resolve, reject) => {
						sass.render({
							data: content,
							includePaths: ['src'],
							sourceMap: false,
							outFile: 'x' // this is necessary, but is ignored
						}, (err, result) => {
							if (err) return reject(err);

							resolve({
								code: result.css.toString(),
								map: result.map ? result.map.toString() : ""
							});
						});
					});
				}
			}
		}),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration —
		// consult the documentation for details:
		// https://github.com/rollup/rollup-plugin-commonjs
		resolve({
			browser: true,
			preferBuiltins: true,
			dedupe: importee => importee === 'svelte' || importee.startsWith('svelte/')
		}),
		commonjs(),
		globals(),
		builtins({ crypto: false }),
		json(),
		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser(),
	],
	// Disable circular dependency warnings from node-tradfri-client
	onwarn(warning, rollupWarn) {
		if (
			!warning.importer.startsWith('node_modules/node-tradfri-client') 
			|| warning.code !== 'CIRCULAR_DEPENDENCY'
		) {
			rollupWarn(warning);
		}
	},
	watch: {
		clearScreen: false
	}
};
```

**Comment by franzwilhelm** [comment]
Just kidding, I wasn't able to solve this with electron 4+, although I got it working in < 4... See here: https://github.com/AlCalzone/node-tradfri-client/issues/91

**Comment by AlCalzone** [comment]
@franzwilhelm Doesn't electron 4+ include NodeJS 10+? If so, node-aead-crypto should not be necessary.
